/*
 * This source file was generated by the Gradle 'init' task
 */
package com.gix.change_object

class App {
    var addressObj: Long = 0
    val greeting: String
        get() {
            return "Hello World!"
        }

    // native interface

    fun setAddress(adr: Long) {
        addressObj = adr
    }

    fun getAddress(): Long {
        return addressObj
    }

    external fun mainNative(): Unit
    external fun doubleGrade(address: Long): Unit
    external fun turnOff(address: Long): Unit

    companion object {
        init {
            System.loadLibrary("change_obj")
        }
    }
}
